version: '3.7'

services:
  bkops:
    image: ethraza/backupops:latest
    build:
      dockerfile: Dockerfile
    container_name: backup-ops
    hostname: bkops.{{.Node.Hostname}}
    environment:
      BOPS_SSH: "on"
      # BOPS_SSH_OPT: "-e -D"
      # BOPS_KEEP_RUNNING: "on"
      BORG_REPO: "/backup/repo"
      BORG_BASE_DIR: "/backup"
      BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK: "yes"
      BORG_RELOCATED_REPO_ACCESS_IS_OK: "yes"

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
      placement:
        # constraints:
        #   - "node.labels.storage == 1"
        preferences:
          - spread: node.labels.storage
      labels:
        - "swarm.cronjob.enable=false"
        - "swarm.cronjob.schedule=10 1 * * *"
        - "swarm.cronjob.skip-running=true"
    ports:
      - target: 22
        protocol: tcp
        mode: ingress
    extra_hosts:
      - "mysql01.localdomain:192.168.0.192"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/storage/backup:/backup
      - /tmp:/tmp
    networks:
      - default


networks:
  default:
    external: true
